### ISSUE TITLE
Travis automatic deploy provider with pypi pops a syntax error

### ISSUE THREAD

**Issue by sylhare** [sylhare/nprime#26]
The command seems to be executed by Travis automatically, but an error occurs:

```bash
Installing deploy dependencies
Successfully installed dpl-pypi-1.10.16
1 gem installed
2021-02-19 17:08:21 URL:https://bootstrap.pypa.io/get-pip.py [1929903/1929903] -> "-" [1]
Traceback (most recent call last):
  File "<stdin>", line 24244, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1171, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1128, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 565, in spec_from_file_location
  File "/tmp/tmpj2mh57gm/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
Couldn't install pip, setuptools, twine or wheel.
```

**Comment by sylhare** [comment]
Apparently it's a bug in the latest version of Travis CI running since 2018! https://github.com/travis-ci/travis-ci/issues/9303
Should be fixed by adding under provider the `edge` to put back to the previous behaviour:

```yaml
  provider: pypi
  edge:
    branch: v1.8.45
```
